types : producten_en_diensten
skos:
  rules :
    skos_rules : /../node_modules/maven-metadata-generator-npm/src/n3/skos-rules.n3
    dcterms_rules : /../node_modules/maven-metadata-generator-npm/src/n3/dcterms-rules.n3
  prefixes :
    concept : https://data.omgeving.vlaanderen.be/id/concept/producten_en_diensten/property/
    collectie : https://data.omgeving.vlaanderen.be/id/collection/producten_en_diensten/
  path: ./main/resources/be/vlaanderen/omgeving/data/id/conceptscheme/
  name: producten_en_diensten
  turtle: .ttl
  jsonld: .jsonld
  xsd: .xsd
  csv: .csv
  rdf_xml: .rdf
  xlsx: .xlsx
  nt: .nt
  json: .json
  parquet: .parquet

source:
  path: ./source/
  codelijst_csv: codelijst-source.csv
  context: context.json
dcat:
  path_catalog: be/vlaanderen/omgeving/data/id/catalog/
  path_dataset: be/vlaanderen/omgeving/data/id/dataset/
  name: codelijst-producten_en_diensten
  dataset_jsonld: dataset.jsonld
  dataset_turtle: dataset.ttl
  catalog_turtle: catalog.ttl
  catalog_jsonld: catalog.jsonld

ap :
  path: ./main/resources/be/vlaanderen/omgeving/data/id/ontology/
  type: ap-constraints
  name: producten_en_diensten
  turtle: .ttl

metadata :
  start_version : 0.0.1
  sparqlservice:
    title: "Sparql service op endpoint https://data.omgeving.vlaanderen.be/sparql"
    description: "Een beschrijving van de sparql service, met de verschillende kenmerken."
    endpoint: https://data.omgeving.vlaanderen.be/sparql
    feature:
      - http://www.w3.org/ns/sparql-service-description#DereferencesURIs
      - http://www.w3.org/ns/sparql-service-description#UnionDefaultGraph
    resultFormat:
      - http://www.w3.org/ns/formats/JSON-LD
      - http://www.w3.org/ns/formats/RDF_XML
      - http://www.w3.org/ns/formats/N-Triples
      - http://www.w3.org/ns/formats/N-Quads
      - http://www.w3.org/ns/formats/SPARQL_Results_CSV
      - http://www.w3.org/ns/formats/SPARQL_Results_XML
      - http://www.w3.org/ns/formats/Turtle
      - http://www.w3.org/ns/formats/SPARQL_Results_JSON
    supportedLanguage: http://www.w3.org/ns/sparql-service-description#SPARQL10Query
  all :
    accessURL : https://github.com/omgeving/codelijst-producten_en_diensten.git
    contactPoint : https://data.omgeving.vlaanderen.be/id/vcard/helpdesk
    license : http://data.vlaanderen.be/id/licentie/modellicentie-gratis-hergebruik/v1.0
    publisher : http://data.vlaanderen.be/id/organisatie/OVO003323
    rightsHolder :  http://data.vlaanderen.be/id/organisatie/OVO003749
    theme :
      - http://eurovoc.europa.eu/2407
      - http://publications.europa.eu/resource/authority/data-theme/ENVI
      - http://vocab.belgif.be/auth/datatheme/ENVI
      - http://www.eionet.europa.eu/gemet/concept/10087
    spatial :
      - http://publications.europa.eu/resource/authority/country/BEL
      - https://sws.geonames.org/3337388/
    accessRights :  http://publications.europa.eu/resource/authority/access-right/PUBLIC
    accrualPeriodicity : http://publications.europa.eu/resource/authority/frequency/IRREG
    dct.language : http://publications.europa.eu/resource/authority/language/NLD
    landingPage  : https://data.omgeving.vlaanderen.be/doc/catalog/codelijst.html
  catalog :
    title: "Catalogus van datasets van codelijsten."
    description: "Catalogus van datasets van codelijsten die onder het domein data.omgeving.vlaanderen.be gepubliceerd worden."
    uri : https://data.omgeving.vlaanderen.be/id/catalog/codelijst
    type: http://www.w3.org/ns/dcat#Catalog
  dataset :
    title: "Dataset van codelijsten i.v.m. luchtzuiveringssystemen voor stallen, gericht op de reductie van stikstofuitstoot."
    description: "Deze dataset bevat codelijsten i.v.m. luchtzuiveringssystemen voor stallen, gericht op de reductie van stikstofuitstoot. De codelijsten hebben een onderlinge samenhang, bv. types van luchtzuiveringssystemen met specifieke regels. De lijsten worden gebruikt bij de een IOT-opzet, i.e. sensordata die aangeleverd worden voor de monitoring van deze systemen. Deze momitoring is opgezet in het kader van het ARMOS-project."
    temporal : https://data.omgeving.vlaanderen.be/id/periodoftime/dataset_omg
    type : http://www.w3.org/ns/dcat#Dataset
    provenance:
      label: "Deze combinatie van codelijsten kwam tot stand in het kader van het ARMOS-project en is een representatie van de logica en typering, die vervat is in regelgeving rond reductie van ammoniakemissie van stallen."
  distribution :
    parquet:
      mediaType: https://www.iana.org/assignments/media-types/application/vnd.apache.parquet
      format: http://publications.europa.eu/resource/authority/file-type/PARQUET
      type: http://www.w3.org/ns/dcat#Distribution
    xlsx:
      title: "Codelijsten ivm. luchtzuiveringssystemen voor stallen, geserialiseerd als excel-formaat."
      description: "Codelijsten ivm. luchtzuiveringssystemen voor stallen, geserialiseerd als excel bestand."
      mediaType: https://www.iana.org/assignments/media-types/application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
      format: http://publications.europa.eu/resource/authority/file-type/XLSX
      type: http://www.w3.org/ns/dcat#Distribution
    csv :
      title: "Codelijsten ivm. luchtzuiveringssystemen voor stallen, geserialiseerd als csv-formaat."
      description: "Codelijsten ivm. luchtzuiveringssystemen voor stallen, geserialiseerd als csv bestand."
      mediaType : https://www.iana.org/assignments/media-types/text/csv
      format : http://publications.europa.eu/resource/authority/file-type/CSV
      type : http://www.w3.org/ns/dcat#Distribution
    nt:
      title: "Codelijsten ivm. luchtzuiveringssystemen voor stallen, geserialiseerd als n-triple-formaat."
      description: "Codelijsten ivm. luchtzuiveringssystemen voor stallen, geserialiseerd als n-triple bestand."
      mediaType: https://www.iana.org/assignments/media-types/application/n-triples
      format: http://publications.europa.eu/resource/authority/file-type/RDF_N_TRIPLES
      type: http://www.w3.org/ns/dcat#Distribution
    json:
      mediaType: https://www.iana.org/assignments/media-types/application/json
      format: http://publications.europa.eu/resource/authority/file-type/JSON
      type: http://www.w3.org/ns/dcat#Distribution
    ttl:
      title: "Codelijsten ivm. luchtzuiveringssystemen voor stallen, geserialiseerd als turtle-formaat."
      description: "Codelijsten ivm. luchtzuiveringssystemen voor stallen, geserialiseerd als turtle bestand."
      mediaType: https://www.iana.org/assignments/media-types/text/turtle
      format: http://publications.europa.eu/resource/authority/file-type/RDF_TURTLE
      type : http://www.w3.org/ns/dcat#Distribution
    jsonld:
      title: "Codelijsten ivm. luchtzuiveringssystemen voor stallen, geserialiseerd als ld+json-formaat."
      description: "Codelijsten ivm. luchtzuiveringssystemen voor stallen, geserialiseerd als json-ld bestand."
      mediaType: https://www.iana.org/assignments/media-types/application/ld+json
      format: http://publications.europa.eu/resource/authority/file-type/JSON_LD
      type : http://www.w3.org/ns/dcat#Distribution
    jar :
      mediaType : https://www.iana.org/assignments/media-types/application/java-archive
      format : http://publications.europa.eu/resource/authority/file-type/JAR
      type :
        - http://www.w3.org/ns/dcat#Distribution
        - http://spdx.org/rdf/terms#Package

prefixes :
  access_right: http://publications.europa.eu/resource/authority/access-right/
  adms: http://www.w3.org/ns/adms#
  assettype: http://purl.org/adms/assettype/
  conceptscheme: https://data.omgeving.vlaanderen.be/id/conceptscheme/
  country: http://publications.europa.eu/resource/authority/country/
  datasets: https://datasets.omgeving.vlaanderen.be/
  datatheme_be: http://vocab.belgif.be/auth/datatheme/
  datatheme_eu: http://publications.europa.eu/resource/authority/data-theme/
  dbo: http://dbpedia.org/ontology/
  dcat: http://www.w3.org/ns/dcat#
  dc: http://purl.org/dc/elements/1.1/
  dcterms: http://purl.org/dc/terms/
  dct: http://purl.org/dc/terms/
  eurovoc: http://eurovoc.europa.eu/
  file_type: http://publications.europa.eu/resource/authority/file-type/
  foaf: http://xmlns.com/foaf/0.1/
  formats: http://www.w3.org/ns/formats/
  frequency: http://publications.europa.eu/resource/authority/frequency/
  gemet: http://www.eionet.europa.eu/gemet/concept/
  schema: https://schema.org/
  licence: http://data.vlaanderen.be/id/licentie/modellicentie-gratis-hergebruik/
  metadata: https://data.omgeving.vlaanderen.be/ns/metadata#
  omg_catalog: https://data.omgeving.vlaanderen.be/id/catalog/
  omg_catalog_doc: https://data.omgeving.vlaanderen.be/doc/catalog/
  omg_collection: https://data.omgeving.vlaanderen.be/id/collection/
  omg_dataservice: https://data.omgeving.vlaanderen.be/id/dataservice/
  omg_dataset_doc: https://data.omgeving.vlaanderen.be/doc/dataset/
  omg_dataset: https://data.omgeving.vlaanderen.be/id/dataset/
  omg_distribution_doc: https://data.omgeving.vlaanderen.be/doc/distribution/
  omg_distribution: https://data.omgeving.vlaanderen.be/id/distribution/
  omg_graphcollection: https://data.omgeving.vlaanderen.be/id/graphcollection/
  omg_graph: https://data.omgeving.vlaanderen.be/id/graph/
  omg_id: https://data.omgeving.vlaanderen.be/id/
  omg_named_graph: https://data.omgeving.vlaanderen.be/id/namedgraph/
  omg_ontology: https://data.omgeving.vlaanderen.be/id/ontology/
  omg_package: https://data.omgeving.vlaanderen.be/id/package/
  omg_periodoftime: https://data.omgeving.vlaanderen.be/id/periodoftime/
  omg_service: https://data.omgeving.vlaanderen.be/id/service/
  omg_vcard: https://data.omgeving.vlaanderen.be/id/vcard/
  ovo: http://data.vlaanderen.be/id/organisatie/
  owl: http://www.w3.org/2002/07/owl#
  repo: https://repo.omgeving.vlaanderen.be/artifactory/release/
  rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns#
  rdfs: http://www.w3.org/2000/01/rdf-schema#
  sd: http://www.w3.org/ns/sparql-service-description#
  skos: http://www.w3.org/2004/02/skos/core#
  spdx: http://spdx.org/rdf/terms#
  ssd: http://www.w3.org/ns/sparql-service-description#
  ts: http://www.w3.org/ns/formats/
  vcard: http://www.w3.org/2006/vcard/ns#
  void: http://rdfs.org/ns/void#
  wise: http://dd.eionet.europa.eu/vocabulary/wise/ObservedProperty/
  xkos: http://rdf-vocabulary.ddialliance.org/xkos#
  xsd: http://www.w3.org/2001/XMLSchema#
  wb: https://data.omgeving.vlaanderen.be/id/concept/waardebepaling/
  normatieve_structuur: https://data.omgeving.vlaanderen.be/id/concept/producten_en_diensten/normatieve_structuur/
  lzp: https://data.omgeving.vlaanderen.be/id/concept/producten_en_diensten/property/
  lzs-type: https://data.omgeving.vlaanderen.be/id/concept/producten_en_diensten/
  lzs-norm: https://data.omgeving.vlaanderen.be/id/concept/producten_en_diensten/norm_bandbreedte/
  lzss: https://data.omgeving.vlaanderen.be/id/concept/producten_en_diensten/status/
  lzsst: https://data.omgeving.vlaanderen.be/id/concept/producten_en_diensten/stalgebruik/
  lzsm: https://data.omgeving.vlaanderen.be/id/concept/producten_en_diensten/medium/
  lzsp: https://data.omgeving.vlaanderen.be/id/concept/producten_en_diensten/eigenschap/
  dr: https://data.omgeving.vlaanderen.be/id/concept/drager/
  lzsns: https://data.omgeving.vlaanderen.be/ns/lzs#
  qudt: http://qudt.org/schema/qudt/
  unit: http://qudt.org/vocab/unit/
  sh: http://www.w3.org/ns/shacl#
  quantitykind: http://qudt.org/vocab/quantitykind/
  ssn: http://www.w3.org/ns/ssn/
  sosa: http://www.w3.org/ns/sosa/
  procedure: https://data.omgeving.vlaanderen.be/id/concept/observatieprocedure/

deploy:
  virtuoso: virtuoso-algemeen
